### ISSUE TITLE
Delete line does not seem to be working in Chrome.

### ISSUE THREAD

**Issue by Jyothis-P** [naseemshah/graph-visualizer#1]
Cannot delete any line once created.

**Comment by naseemshah** [comment]
Looks like i didn't even implemented the feature 😅

![image](https://user-images.githubusercontent.com/44234669/81851423-0d006d00-9577-11ea-9933-71654b8e3b5a.png)

**Comment by naseemshah** [comment]
Fixed the Issue. (see commit a309646 )

![gvis issue 1](https://user-images.githubusercontent.com/44234669/81856048-d4b05d00-957d-11ea-8fcc-a357b71390d8.gif)
