### ISSUE TITLE
Cannot drag a node on top of another node.

### ISSUE THREAD

**Issue by Jyothis-P** [naseemshah/graph-visualizer#2]
When you try to drag Node 1 above Node 4, Node 1 is deselected and Node 4 is selected instead. PFA image for getting a better idea of the issue. (Node 4 is any node with a higher number that Node 1)
![gfmeme](https://user-images.githubusercontent.com/33348514/81848762-3ddea300-9573-11ea-8c1e-b22935b604f3.jpg)

**Comment by naseemshah** [comment]
That pic was very accurate representation 😂. Working on it ✌. The higher node doesn't swap with lower node, **but lower node swaps.**

**Comment by naseemshah** [comment]
this is fixed now :)

since you memed, i also did 😂:
![gvis meme](https://user-images.githubusercontent.com/44234669/82058162-fe829480-96e1-11ea-8794-124fa6360fd9.gif)


Please Reopen the issue if there is the swapping problem again.
