### ISSUE TITLE
After deleting every node, the last node remains in the nodes browser. Same issue happens with lines.

### ISSUE THREAD

**Issue by NithinRG** [naseemshah/graph-visualizer#5]

**Comment by naseemshah** [comment]
Cool! I had this bug while I was testing. Eventually forgot to fix it. Thanks for reporting.

**Comment by naseemshah** [comment]
Implemented the fix. Same works for the lines tree browser.

![gvis issue 4](https://user-images.githubusercontent.com/44234669/81971192-52d43880-963e-11ea-9818-2bda9e987cdf.gif)
